version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  go-app:
    build: .
    container_name: go-app
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
      - mongodb

  worker:
    build: .
    container_name: worker
    environment:
      ROLE: worker
      MONGODB_URI: mongodb://mongodb:27017
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
      - mongodb

volumes:
  mongo_data: